/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-02-09 09:43:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=PT+Sans');\r\n");
      out.write("body{\r\n");
      out.write("width=100%;\r\n");
      out.write("background-repeat:no-repeat;\r\n");
      out.write("background-size:cover;\r\n");
      out.write("}img {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    left: 36%;\r\n");
      out.write("    top: 10%;\r\n");
      out.write("}\r\n");
      out.write("button.btn.btn-outline-info {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    font-size: 35px;\r\n");
      out.write("    top: 33%;\r\n");
      out.write("    left: 20%;\r\n");
      out.write("    width:250px;\r\n");
      out.write("    border: 2px solid color red;\r\n");
      out.write("    border: 3px solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#add{\r\n");
      out.write("  background-image: url('./imgtry/addCont.gif');\r\n");
      out.write("  background-size: 100% 100%;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  color: #3ad2ff;\r\n");
      out.write("  left:27%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#add:hover{\r\n");
      out.write("background:transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#view:hover{\r\n");
      out.write("background:transparent;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#view{\r\n");
      out.write(" left: 55%;\r\n");
      out.write(" border: 3px solid;\r\n");
      out.write(" border: 3px solid;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    color: #ff15e2;\r\n");
      out.write("      background-image: url('./imgtry/viewContact.gif');\r\n");
      out.write("  background-size: 100% 100%;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#search{\r\n");
      out.write("top:63%;\r\n");
      out.write("left:41%;\r\n");
      out.write("  background-image: url('./imgtry/search.gif');\r\n");
      out.write("  background-size: 100% 100%;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search:hover{\r\n");
      out.write("background:transparent;\r\n");
      out.write("color:#3ad2ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".logout img{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 105px;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    left: 85%;\r\n");
      out.write("    top: 68%;\r\n");
      out.write("    height: 106px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout img:hover{\r\n");
      out.write("\r\n");
      out.write("   border:3px solid #28c3ff;\r\n");
      out.write("}\r\n");
      out.write(".pic{\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  background: linear-gradient(130deg, #74b9ff, #e66767);\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  background-size: 200% 200%;\r\n");
      out.write("  animation: animated-gradient 2s linear infinite;\r\n");
      out.write("}\r\n");
      out.write(".pic img{\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100px;\r\n");
      out.write("  height: 100px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write(".pic {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    height: 107px;\r\n");
      out.write("    width: 113px;\r\n");
      out.write("    left: 4%;\r\n");
      out.write("    top: 2%;\r\n");
      out.write("}\r\n");
      out.write("img#profile {\r\n");
      out.write("    left: 6%;\r\n");
      out.write("    top: 4%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url(https://img.freepik.com/premium-photo/blue-purple-neon-square-black-brick-wall-background_161844-394.jpg?w=2000) ;\">\r\n");
      out.write("   <div class=\"pic\">\r\n");
      out.write("      ");

      
      String img=(String)session.getAttribute("ProfileImg");
      System.out.println(img);
      if(img!=null){
    	  
      
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        <a href=\"./profile.jsp\"><img src=\"./imgtry/");
      out.print(img);
      out.write("\" id=\"profile\" alt=\"\"></a>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   <img src=\"./imgtry/welcome.jpeg\" alt=\"logo\">\r\n");
      out.write("   <div class=\"add-Cont\">\r\n");
      out.write("   <a href=\"./addContact.jsp\" id= \"addCont\"><button type=\"button\" class=\"btn btn-outline-info\" id=\"add\" >ADD<br>CONTACTS</button></a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"add-Cont\">\r\n");
      out.write("  <a href = \"./ContactServlet?action=viewContact\" ><button type=\"button\" class=\"btn btn-outline-info\" id=\"view\">VIEW<br>CONTACTS</button></a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"add-Cont\">\r\n");
      out.write("  <a href = \"./ContactServlet?action=viewContact\" ><button type=\"button\" class=\"btn btn-outline-info\" id=\"search\">SEARCH<br>CONTACTS</button>\r\n");
      out.write("   </div>  \r\n");
      out.write("   <div class=\"add-Cont\">\r\n");
      out.write("  <a href=\"./UserServlet?action=logout\" class=\"logout\" id=\"logout\"><img alt=\"logut\" src=\"./imgtry/logout.jpeg\"></a>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
