/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-02-09 09:16:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dollop.entity.User;
import com.dollop.service.PhoneBookDaoImpl;
import com.dollop.DAO.PhoneBookDAO;
import java.util.*;
import com.dollop.entity.Contacts;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dollop.service.PhoneBookDaoImpl");
    _jspx_imports_classes.add("com.dollop.entity.User");
    _jspx_imports_classes.add("com.dollop.entity.Contacts");
    _jspx_imports_classes.add("com.dollop.DAO.PhoneBookDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" \r\n");
      out.write("          href=\r\n");
      out.write("\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  font-family: \"Ubuntu\", sans-serif;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("  background: url(bg.jpg) no-repeat center;\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card{\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  top:30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-header{\r\n");
      out.write("  background: #2c3a47;\r\n");
      out.write("  padding: 60px 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic{\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  background: linear-gradient(130deg, #74b9ff, #e66767);\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  background-size: 200% 200%;\r\n");
      out.write("  animation: animated-gradient 2s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes animated-gradient{\r\n");
      out.write("  25%{\r\n");
      out.write("    background-position: left bottom;\r\n");
      out.write("  }\r\n");
      out.write("  50%{\r\n");
      out.write("    background-position: right bottom;\r\n");
      out.write("  }\r\n");
      out.write("  75%{\r\n");
      out.write("    background-position: right top;\r\n");
      out.write("  }\r\n");
      out.write("  100%{\r\n");
      out.write("    background-position: left top;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic img{\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100px;\r\n");
      out.write("  height: 100px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".name{\r\n");
      out.write("  color: #f2f2f2;\r\n");
      out.write("  font-size: 28px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".desc{\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  color: #e66767;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sm{\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  margin: 20px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sm a{\r\n");
      out.write("  color: #f2f2f2;\r\n");
      out.write("  width: 56px;\r\n");
      out.write("  font-size: 22px;\r\n");
      out.write("  transition: .3s linear;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sm a:hover{\r\n");
      out.write("  color: #e66767;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-btn{\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding: 12px 50px;\r\n");
      out.write("  color: #e66767;\r\n");
      out.write("  border: 2px solid #e66767;\r\n");
      out.write("  border-radius: 6px;\r\n");
      out.write("  margin-top: 16px;\r\n");
      out.write("  transition: .3s linear;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-btn:hover{\r\n");
      out.write("  background: #e66767;\r\n");
      out.write("  color: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer{\r\n");
      out.write("  background: #f4f4f4;\r\n");
      out.write("  padding: 60px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".numbers{\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item{\r\n");
      out.write("  flex: 1;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("  color: #e66767;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item span{\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: #2c3a47;\r\n");
      out.write("  font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".border{\r\n");
      out.write("  width: 1px;\r\n");
      out.write("  height: 30px;\r\n");
      out.write("  background: #bbb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("img#back {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 2%;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    left: 0%;\r\n");
      out.write("}\r\n");
      out.write("#bck{\r\n");
      out.write("background-color: transparent;\r\n");
      out.write("border:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    border: 0.40rem solid #a5d2ff;\r\n");
      out.write("    top: 10%;\r\n");
      out.write("    background: #000000c7;\r\n");
      out.write("    top: -109%;\r\n");
      out.write("    box-shadow: 0px 0px 10px 3px #ccc;\r\n");
      out.write("    transition:1s;\r\n");
      out.write("}\r\n");
      out.write(".card span{\r\n");
      out.write("position: absolute;\r\n");
      out.write("right:0px;\r\n");
      out.write("top:0px;\r\n");
      out.write("color:white;\r\n");
      out.write("background: red;\r\n");
      out.write("text-align:center;\r\n");
      out.write("line-height:30px;\r\n");
      out.write("height:30px;\r\n");
      out.write("width:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2{\r\n");
      out.write("  padding-top: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control{\r\n");
      out.write("  background-color: #f8f9fa;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  padding: 25px 15px;\r\n");
      out.write("  margin-bottom: 1.3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    border: 3px solid #da5767;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:hover {\r\n");
      out.write("\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    border: 3px solid #da5767;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn{\r\n");
      out.write("  padding: 0.6rem 1.2rem;\r\n");
      out.write("  background: #da5767;\r\n");
      out.write("  border: 2px solid #da5767;\r\n");
      out.write("}\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    background-color: #df8c96;\r\n");
      out.write("    border-color: #df8c96;\r\n");
      out.write("  transition: .3s;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".showoverlay{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write(".showedit {\r\n");
      out.write("    top: -120%;\r\n");
      out.write("    width: 283%;\r\n");
      out.write("    left: -89%;\r\n");
      out.write("}\r\n");
      out.write(".profile-card {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -4%;\r\n");
      out.write("}\r\n");
      out.write("a#con{\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("color: #e1566e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"profile-card\">\r\n");
      out.write("    <div class=\"card-header\">\r\n");
      out.write("  <form action=\"./FileHandler?action=updateProfile\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("      <div class=\"pic\">\r\n");
      out.write("      ");

      
      String img=(String)session.getAttribute("ProfileImg");
      System.out.println(img);
      if(img!=null){
    	  
      
      out.write("\r\n");
      out.write("        <img src=\"./imgtry/");
      out.print(img);
      out.write("\" alt=\"\">\r\n");
      out.write("        ");
}
      else
      
      out.write("<img src=\"./imgtry/profile.jpg\" alt=\"\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <i class=\"fa fa-folder\"></i><input type=\"file\" id=\"take\"name=\"file\">\r\n");
      out.write("    <input type=\"submit\" id=\"val\"value=\"upload\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");

PhoneBookDAO ph = new PhoneBookDaoImpl();
User us1 = ph.getUser((Integer)session.getAttribute("login"));

      out.write("\r\n");
      out.write("      <div class=\"name\">");
      out.print(us1.getName());
      out.write("</div>\r\n");
      out.write("      <a data-confirm=\"Are you sure?\" class=\"contact-btn\" href=\"./UserServlet?action=editUser\" rel=\"nofollow\">Edit Profile </a>\r\n");
      out.write("      <a href=\"\" class=\"contact-btn\">View Profile</a>\r\n");
      out.write("      <a href=\"./addContact.jsp\" class=\"contact-btn\">Add-Contacts</a>\r\n");
      out.write("      ");

      try{
      List<Contacts> list = ph.getContacts((Integer)session.getAttribute("login"));
      
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-footer\">\r\n");
      out.write("      <div class=\"numbers\">\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("          <span>");
      out.print(list.size() );
      out.write("</span>\r\n");
      out.write("          ");
}catch(Exception e){} 
      out.write("\r\n");
      out.write("          <a href=\"./ContactServlet?action=viewContact\" id=\"con\">Contacts</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"border\"></div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("          <span>12</span>\r\n");
      out.write("          Favrouits\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");

try{
if((Boolean)request.getAttribute("on"))
{

      out.write("\r\n");
      out.write("   <body onload=\"showModel()\"></body>\r\n");
      out.write("   \r\n");
      out.write("   ");
}}catch(Exception e){} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");

try{
if((Boolean)request.getAttribute("on"))
{
User us =(User)request.getAttribute("User");
if(us!=null)
{
	

      out.write("\r\n");
      out.write("<div class=\"overlay\" onclick=\"closeModel()\" ></div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"row justify-content-center\">\r\n");
      out.write("  <div class=\"col-md-5\">\r\n");
      out.write("   <div class=\"card\">\r\n");
      out.write("   <span>&times;</span>\r\n");
      out.write("      <h2 class=\"card-title text-center\" style=color:indianred><b>EDIT-CONTACT</b></h2>\r\n");
      out.write("       <div class=\"card-body py-md-4\">\r\n");
      out.write("        <form _lpchecked=\"1\" action=\"./UserServlet?action=saveUser&id=");
      out.print(us.getId() );
      out.write("\" method=\"post\">\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"name\"  name=\"name\" placeholder=\"name\" value=");
      out.print(us.getName() );
      out.write(" required=\"required\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"email\"   name=\"email\" value = ");
      out.print(us.getEmail() );
      out.write("  required=\"required\">\r\n");
      out.write("                            </div>                                               \r\n");
      out.write("   <div class=\"form-group\">\r\n");
      out.write("     <input type=\"text\" class=\"form-control\" id=\"MobileNo\" placeholder=\"Mobile Number\"  id=\"contact\" name=\"MobileNo\" value=");
      out.print(us.getContact() );
      out.write("  required=\"required\">\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"form-group\">\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"Address\" placeholder=\"password\"  name=\"password\"  value=");
      out.print(us.getPassword() );
      out.write("  required=\"required\">\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("   \r\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"saveUser\" >\r\n");
      out.write("                                <button class=\"btn btn-primary\">SAVE</button>   \r\n");
      out.write("          </div>\r\n");
      out.write("     ");
}}}catch(Exception e){} 
      out.write("  \r\n");
      out.write("       </form>\r\n");
      out.write("     </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <a href=\"./dashboard.jsp\" id=\"bck\"><img alt=\"\"  id=\"back\" src=\"./imgtry/back.png\"></a>  \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function showModel(){\r\n");
      out.write("	document.querySelector('.overlay').classList.add('showoverlay');\r\n");
      out.write("	document.querySelector('.card').classList.add('showedit');\r\n");
      out.write("}\r\n");
      out.write("function closeModel(){\r\n");
      out.write("	document.querySelector('.overlay').classList.remove('showoverlay');\r\n");
      out.write("	document.querySelector('.card').classList.remove('showedit');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var btnedit = document.querySelector(\".contact-btn\");\r\n");
      out.write("btnedit.addEventListener(\"click\",showModel)\r\n");
      out.write("\r\n");
      out.write("var c = document.querySelector(\"span\");\r\n");
      out.write("c.addEventListener(\"click\",closeModel)\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
