/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-02-14 07:56:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.dollop.entity.Contacts;

public final class viewContact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dollop.entity.Contacts");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=PT+Sans');\r\n");
      out.write(".overlay{\r\n");
      out.write("width: 100%;\r\n");
      out.write("height: 100vh;\r\n");
      out.write("top: 0%;\r\n");
      out.write("position: fixed;\r\n");
      out.write("background: rgba(0, 0, 0, 0.5);\r\n");
      out.write("z-index: -1;\r\n");
      out.write("opacity: 0;\r\n");
      out.write("transition:1s;\r\n");
      out.write("}\r\n");
      out.write("*{\r\n");
      out.write("margin:0px;\r\n");
      out.write("padding:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    border: 0.40rem solid #a5d2ff;\r\n");
      out.write("    top: 10%;\r\n");
      out.write("    background: #000000c7;\r\n");
      out.write("    top: -109%;\r\n");
      out.write("    box-shadow: 0px 0px 10px 3px rgb(255, 85, 229);\r\n");
      out.write("    transition:1s;\r\n");
      out.write("}\r\n");
      out.write(".card span{\r\n");
      out.write("position: absolute;\r\n");
      out.write("right:0px;\r\n");
      out.write("top:0px;\r\n");
      out.write("color:white;\r\n");
      out.write("background: red;\r\n");
      out.write("text-align:center;\r\n");
      out.write("line-height:30px;\r\n");
      out.write("height:30px;\r\n");
      out.write("width:30px;\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2{\r\n");
      out.write("  padding-top: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color:white;\r\n");
      out.write("    background-color: #df8c96;\r\n");
      out.write("    border-color: #df8c96;\r\n");
      out.write("  transition: .3s;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("  color:white; \r\n");
      out.write("  padding: 0.6rem 1.2rem;\r\n");
      out.write("  background: #da5767;\r\n");
      out.write("  border: 2px solid #da5767;\r\n");
      out.write("  transition:.3s;\r\n");
      out.write("  border-radius:7px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".form-control{\r\n");
      out.write("  background-color: #f8f9fa;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  padding: 25px 15px;\r\n");
      out.write("  margin-bottom: 1.3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    border: 3px solid #da5767;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:hover {\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    border: 3px solid #da5767;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn{\r\n");
      out.write("  padding: 0.6rem 1.2rem;\r\n");
      out.write("  background: #da5767;\r\n");
      out.write("  border: 2px solid #da5767;\r\n");
      out.write("}\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("    background-color: #df8c96;\r\n");
      out.write("    border-color: #df8c96;\r\n");
      out.write("  transition: .3s;\r\n");
      out.write("}\r\n");
      out.write(".showoverlay{\r\n");
      out.write("opacity:1;\r\n");
      out.write("z-index:-1;\r\n");
      out.write("}\r\n");
      out.write(".showedit{\r\n");
      out.write("top:15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write(" background: #fff;\r\n");
      out.write("  background-image:url(https://media.istockphoto.com/id/1281751596/video/blue-purple-neon-laser-squares-technology-motion-background.jpg?s=640x640&k=20&c=epaW0qyxpCPje6n9eB89uKmiW7zld4nCf7__BkbNHgU=);\r\n");
      out.write("  background-repeat:no-repeat;\r\n");
      out.write("  background-attachment:fixed;\r\n");
      out.write("  background-size:cover;\r\n");
      out.write("  font-family: 'PT Sans', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("table.table.table-hover.table-dark {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 28%;\r\n");
      out.write("    left:15%;\r\n");
      out.write("    width: 75%;\r\n");
      out.write("}\r\n");
      out.write(".table-dark {\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color: #212529;\r\n");
      out.write("}#add-button {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    background: #261c1ccc;\r\n");
      out.write("    color: white;\r\n");
      out.write("    height: 43px;\r\n");
      out.write("    left: 17%;\r\n");
      out.write("    top: 21%;\r\n");
      out.write("    width: 15%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    display: block;\r\n");
      out.write("    border: 2px solid white;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("a#add-button:hover {\r\n");
      out.write("    background: white;\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-decoration: dotted;\r\n");
      out.write("    transition: .6s;\r\n");
      out.write("}\r\n");
      out.write("img {\r\n");
      out.write("    POSITION: ABSOLUTE;\r\n");
      out.write("    left: 18%;\r\n");
      out.write("    top: 3%;\r\n");
      out.write("    border-radius: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input.form-control.rounded {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 170%;\r\n");
      out.write("    left: 64%;\r\n");
      out.write("    width: 18%;\r\n");
      out.write("}\r\n");
      out.write(".btn-edit{\r\n");
      out.write("background: transparent;\r\n");
      out.write("    border: 2px solid #739aff\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-delete{\r\n");
      out.write("background: transparent;\r\n");
      out.write("}\r\n");
      out.write("form.form-inline.my-2.my-lg-0 {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 19%;\r\n");
      out.write("    left: 54%;\r\n");
      out.write("}\r\n");
      out.write("button#search {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 3%;\r\n");
      out.write("    left: 96%;\r\n");
      out.write("    background: #2d9ed3;\r\n");
      out.write("    color: white;\r\n");
      out.write("    height: 48px;\r\n");
      out.write("    border: 2px solid #7ce9ff;\r\n");
      out.write("}\r\n");
      out.write("th#no_data {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    left: 38%;\r\n");
      out.write("}\r\n");
      out.write("img#back {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 67%;\r\n");
      out.write("    height: 77px;\r\n");
      out.write("    left: 85%;\r\n");
      out.write("}\r\n");
      out.write("#bck{\r\n");
      out.write("background-color: transparent;\r\n");
      out.write("border:0px;\r\n");
      out.write("}\r\n");
      out.write("form#f {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -1;\r\n");
      out.write("    top: 65px;\r\n");
      out.write("    left: 925px;\r\n");
      out.write("}\r\n");
      out.write("button#opt {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 81%;\r\n");
      out.write("    top: 22%;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    width: 157px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background: #12101000;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("div#menu {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 85%;\r\n");
      out.write("    top: 21%;\r\n");
      out.write("}\r\n");
      out.write(".delt {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 78%;\r\n");
      out.write("    top: 22%;\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    z-index: -1;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".showbutton{\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- <div class=\"input-group\">\r\n");
      out.write("  <input type=\"search\"  id=\"name\" name=\"name\"  class=\"form-control rounded\" placeholder=\"Search\"  />\r\n");
      out.write("  <a href=\"./ContactServlet?action=search\"><button type=\"button\" id=\"search-btn\" class=\"btn btn-outline-primary\">search</button></a>\r\n");
      out.write("</div>\r\n");
      out.write(" -->\r\n");
      out.write(" <div class=\"dropdown show\" id=\"menu\">\r\n");
      out.write("  <a class=\"btn btn-secondary dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("   :\r\n");
      out.write("  </a>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("   <button onclick=\"select()\" class=\"dropdown-item\">SELECT MULTIPLE</button>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"./ContactServlet?action=sorty&id=1\">Sort A-Z</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"./ContactServlet?action=sorty&id=2\">Sort Z-A</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<form class=\"form-inline my-2 my-lg-0\" action=\"./ContactServlet\">\r\n");
      out.write("      <input class=\"form-control mr-sm-2\"  name=\"name\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("      <input type=\"hidden\" name=\"action\" id=\"search\" value=\"search\">\r\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" id=\"search\" type=\"submit\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("<a href=\"./addContact.jsp\" id=\"add-button\" > ADD CONTACT</a>\r\n");
      out.write("<img alt=\"\" src=\"./imgtry/viewContact.png\">\r\n");
      out.write("<table class=\"table table-hover table-dark\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">#ID</th>\r\n");
      out.write("      <th scope=\"col\">NAME</th>\r\n");
      out.write("      <th scope=\"col\">EMAIL</th>\r\n");
      out.write("      <th scope=\"col\">MOBILENO</th>\r\n");
      out.write("      <th scope=\"col\">ADDRESS</th>\r\n");
      out.write("      <th scope=\"col\">ACTION</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("  ");

  try{
    List<Contacts> list = (ArrayList)request.getAttribute("list");
    List<Contacts> list_search = (ArrayList)request.getAttribute("list_search");
    String msg="NO CONTACTS FOUND";
    if(list==null && list_search==null)
    {
    
      out.write("	\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th id=\"no_data\" scope=\"row\">");
      out.print(msg);
      out.write("</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 
    }
    int i=0;
    if(list_search!=null)
    {
        	list=list_search;
    }
    for(Contacts item:list)
    {
    
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">");
      out.print(i=i+1 );
      out.write("</th>\r\n");
      out.write("      <td>");
      out.print(item.getName() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(item.getEmail() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(item.getMobile() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(item.getAddress() );
      out.write("</td>\r\n");
      out.write("      <td> <a data-confirm=\"Are you sure?\" class=\"btn-edit\" href=\"./ContactServlet?action=editContact&id=");
      out.print(item.getId());
      out.write("\" rel=\"nofollow\">EDIT </a>\r\n");
      out.write("      <a href=\"./ContactServlet?action=delete&id=");
      out.print(item.getId());
      out.write("\" class=\"btn-delete\" onclick=\"return confirm('Are you sure you want to delete this item?');\">Delete</a>\r\n");
      out.write("      <form action=\"./ContactServlet\" id=\"f\">\r\n");
      out.write("      <input type=\"hidden\" class=\"select\" name=\"check\" value=");
      out.print(item.getId());
      out.write(">  \r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
}}catch(Exception e){}
      out.write("\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"multi\">\r\n");
      out.write("    <button onclick=\"find()\" class=\"delt\">DELETE</button>\r\n");
      out.write(" </form>\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

try{
if((Boolean)request.getAttribute("on"))
{
Contacts con =(Contacts)request.getAttribute("Contact");
if(con!=null)
{
	

      out.write("\r\n");
      out.write("<div class=\"overlay\" onclick=\"closeModel()\" ></div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"row justify-content-center\">\r\n");
      out.write("  <div class=\"col-md-5\">\r\n");
      out.write("   <div class=\"card\">\r\n");
      out.write("   <span>&times;</span>\r\n");
      out.write("      <h2 class=\"card-title text-center\" style=color:indianred><b>EDIT-CONTACT</b></h2>\r\n");
      out.write("       <div class=\"card-body py-md-4\">\r\n");
      out.write("        <form _lpchecked=\"1\" action=\"./ContactServlet?action=saveContact&id=");
      out.print(con.getId() );
      out.write("\" method=\"post\">\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"name\"  name=\"name\" placeholder=\"name\" value=");
      out.print(con.getName() );
      out.write(" required=\"required\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"email\"   name=\"email\" value = ");
      out.print(con.getEmail() );
      out.write("  required=\"required\">\r\n");
      out.write("                            </div>                                               \r\n");
      out.write("   <div class=\"form-group\">\r\n");
      out.write("     <input type=\"text\" class=\"form-control\" id=\"MobileNo\" placeholder=\"Mobile Number\"   name=\"MobileNo\" value=");
      out.print(con.getMobile() );
      out.write("  required=\"required\">\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"form-group\">\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"Address\" placeholder=\"Address\"  name=\"Address\"  value=");
      out.print(con.getAddress() );
      out.write("  required=\"required\">\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("   \r\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"saveContact\" >\r\n");
      out.write("                                <button class=\"btn btn-primary\">SAVE</button>   \r\n");
      out.write("          </div>\r\n");
      out.write("     ");
}}}catch(Exception e){} 
      out.write("  \r\n");
      out.write("       </form>\r\n");
      out.write("     </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");

try{
if((Boolean)request.getAttribute("on"))
{

      out.write("\r\n");
      out.write("   <body onload=\"showModel()\"></body>\r\n");
      out.write("   \r\n");
      out.write("   ");
}}catch(Exception e){} 
      out.write("\r\n");
      out.write("        <a href=\"./dashboard.jsp\" id=\"bck\"><img alt=\"\"  id=\"back\" src=\"./imgtry/back.png\"></a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("function showModel(){\r\n");
      out.write("	document.querySelector('.overlay').classList.add('showoverlay');\r\n");
      out.write("	document.querySelector('.card').classList.add('showedit');\r\n");
      out.write("}\r\n");
      out.write("function closeModel(){\r\n");
      out.write("	document.querySelector('.overlay').classList.remove('showoverlay');\r\n");
      out.write("	document.querySelector('.card').classList.remove('showedit');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var btnedit = document.querySelector(\".btn-edit\");\r\n");
      out.write("btnedit.addEventListener(\"click\",showModel)\r\n");
      out.write("\r\n");
      out.write("var c = document.querySelector(\"span\");\r\n");
      out.write("c.addEventListener(\"click\",closeModel)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function select(){\r\n");
      out.write("	var t=document.getElementsByClassName('select');\r\n");
      out.write("	console.warn(t[0].innerHTML)\r\n");
      out.write("	if(t[0].type==\"hidden\"){\r\n");
      out.write("	for(let i=0;i<t.length;i++){\r\n");
      out.write("		t[i].type=\"checkbox\";\r\n");
      out.write("	}\r\n");
      out.write("	document.querySelector('.delt').classList.add('showbutton');\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	else\r\n");
      out.write("		{\r\n");
      out.write("		for(let i=0;i<t.length;i++){\r\n");
      out.write("			t[i].type=\"hidden\";\r\n");
      out.write("		}\r\n");
      out.write("		document.querySelector('.delt').classList.remove('showbutton');\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
